### ISSUE TITLE
DateTimeParseException for invalid "remind" commands

### ISSUE THREAD

**Issue by alcen** [AY1920S2-CS2103T-F09-1/main#94]
When something like `remind 1` is run, it will cause an uncaught DateTimeParseException

Full stack trace:
```
Caused by: java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
        at java.base/java.time.LocalDate.parse(LocalDate.java:428)
        at java.base/java.time.LocalDate.parse(LocalDate.java:413)
        at csdev.couponstash.logic.commands.RemindCommand.execute(RemindCommand.java:91)
        at csdev.couponstash.logic.LogicManager.execute(LogicManager.java:45)
        at csdev.couponstash.ui.MainWindow.executeCommand(MainWindow.java:175)
        at csdev.couponstash.ui.CommandBox.handleCommandEntered(CommandBox.java:38)
        ... 59 more
```

**Comment by ChesterSim** [comment]
@kevvvinn can check if this bug is still happening? Please fix it if it still occurs, if not do close the issue!
